#if 0
// Copyright (C) 2023-2026 University Corporation for Atmospheric Research
// SPDX-License-Identifier: Apache-2.0

// This file defines error categories and codes for MIAM
#endif

#define MIAM_ERROR_CATEGORY_CONFIGURATION                       "MIAM Configuration"
#define MIAM_CONFIGURATION_PHASE_NAME_REQUIRED 1
#define MIAM_CONFIGURATION_UNSUPPORTED_PROPERTY 2
#define MIAM_CONFIGURATION_MISSING_REQUIRED_PARAMETER 3
#define MIAM_CONFIGURATION_MUTUALLY_EXCLUSIVE_PARAMETERS 4
#define MIAM_CONFIGURATION_MISSING_GAS_SPECIES 5
#define MIAM_CONFIGURATION_ALGEBRAIC_SPECIES_NOT_FOUND_IN_PRODUCTS 7
#define MIAM_CONFIGURATION_MISSING_STATE_PARAMETER 8
#define MIAM_CONFIGURATION_INVALID_PARAMETER 9

#define MIAM_ERROR_CATEGORY_INTERNAL                            "MIAM Internal"
#define MIAM_INTERNAL_MISSING_PHASE_PREFIX 100
#define MIAM_INTERNAL_MISSING_STATE_PARAMETER 101
#define MIAM_INTERNAL_MISSING_STATE_VARIABLE 102
#define MIAM_INTERNAL_DUPLICATE_STATE_PREFIX 103
